# This is a target-hardware configuration file intended to be used in a Yocto / systemd environment.

debug: false

http:
  port: 8080
  api_key: "@@HAFH_SERVER_API_KEY@@"
  max_requests_per_second: 5

# Ngrok configuration for tunneling HTTP traffic to a public URL.
ngrok:
  enabled: true
  auth_token: "@@HAFH_SERVER_NGROK_AUTH_TOKEN@@"
  region: "us"
  domain: "@@HAFH_SERVER_NGROK_SUBDOMAIN@@"

mqtt:
  address: "0.0.0.0"
  port: 8883
  cert_path: "/data/hafh-server/certs/server.crt"
  key_path: "/data/hafh-server/certs/server.key"
  ca_path: "/data/hafh-server/certs/ca.crt"

database:
  path: "/data/hafh-server/hafh.db"
