name: Build and Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Build, Format, and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Install Dependencies
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          PATH=$GOPATH/bin:$PATH

      - name: Verify Go Modules
        run: |
          go mod tidy
          git diff --exit-code || (echo "Run 'go mod tidy' locally" && exit 1)

      - name: Check Formatting
        run: |
          make format
          git diff --exit-code || (echo "Run 'make format' locally" && exit 1)

      - name: Lint
        run: make lint

      - name: Build
        run: make build
